pipeline:
  build:
    image: gtmanfred/kitchen-salt:latest
    environment:
      - DOCKER_HOST=tcp://172.18.0.1:2375
      - KITCHEN_YAML=.kitchen.docker.yml
    commands:
      - bundle install
      - bundle exec kitchen create nitrogen -l warn -c 4
      - bundle exec kitchen converge nitrogen
  verify:
    image: gtmanfred/kitchen-salt:latest
    environment:
      - DOCKER_HOST=tcp://172.18.0.1:2375
      - KITCHEN_YAML=.kitchen.docker.yml
    commands:
      - bundle install
      - python3 -m pip install -r requirements.txt
      - bundle exec kitchen verify nitrogen
  clean:
    when:
      status:
        - failure
        - success
    image: gtmanfred/kitchen-salt:latest
    environment:
      - DOCKER_HOST=tcp://172.18.0.1:2375
      - KITCHEN_YAML=.kitchen.docker.yml
    commands:
      - bundle install
      - bundle exec kitchen list nitrogen
      - bundle exec kitchen destroy nitrogen
when:
  branch:
    include:
      - master
