pipeline:
  build:
    image: gtmanfred/kitchen-salt:latest
    environment:
      - DOCKER_HOST=tcp://172.18.0.1:2375
    commands:
      - bundle install
      - bundle exec kitchen create all -l warn -c 4
      - bundle exec kitchen converge all
  verify:
    image: gtmanfred/kitchen-salt:latest
    environment:
      - DOCKER_HOST=tcp://172.18.0.1:2375
    commands:
      - bundle install
      - python3 -m pip install -r requirements.txt
      - bundle exec kitchen verify all
  clean:
    when:
      status:
        - failure
        - success
    image: gtmanfred/kitchen-salt:latest
    environment:
      - DOCKER_HOST=tcp://172.18.0.1:2375
    commands:
      - bundle install
      - bundle exec kitchen list
      - bundle exec kitchen destroy all
when:
  branch:
    include:
      - master
