language: ruby
services:
  - docker
addons:
  apt:
    packages:
    - curl
    - git
    - python3-pip
rvm:
  - ruby
dist: trusty
before_install:
  - add-apt-repository ppa:jonathonf/python-3.6
  - apt-get update && apt-get install python
  - pip3 install --user -r test-requirements.txt
script:
  # Setup for tests
  - bundle exec kitchen create -l warn -c 3
  # Provision containers
  - bundle exec kitchen converge
  # Run test-kitchen with docker driver:
  - bundle exec kitchen verify
after_script:
  - bundle exec kitchen list
  - bundle exec kitchen destroy all
