language: python
services:
  - docker
addons:
  apt:
    packages:
    - curl
    - git
    - ruby-bundler
python:
  - 3.6
dist: trusty
install:
  - bundle install
  - pip3 install --user -r test-requirements.txt
script:
  # Setup for tests
  - bundle exec kitchen create -l warn -c 3
  # Provision containers
  - bundle exec kitchen converge
  # Run test-kitchen with docker driver:
  - bundle exec kitchen verify
after_script:
  - bundle exec kitchen list
  - bundle exec kitchen destroy all
