version: 2.0
jobs:
  test:
    machine:
      image: circleci/classic:latest
      enabled: true
    steps:
      - checkout
      - run:
          name: Disable AppArmor
          command: |
            sudo service apparmor teardown
            sudo apt-get remove -y apparmor
      - run:
          name: Install Test Kitchen
          command: |
            bundle install
            git -C /opt/circleci/.pyenv/ pull
            pyenv install 3.6.2
            pyenv global 3.6.2
            pip install -r requirements.txt
      - run:
          name: Setup Containers
          command: |
            export KITCHEN_YAML=.kitchen.docker.yml
            bundle exec kitchen create nitrogen -l warn -c 4
            bundle exec kitchen converge nitrogen
      - run:
          name: Verify Environments
          command: |
            export KITCHEN_YAML=.kitchen.docker.yml
            bundle exec kitchen verify nitrogen
      - run:
          name: Cleanup Containers
          command: |
            export KITCHEN_YAML=.kitchen.docker.yml
            bundle exec kitchen list nitrogen
            bundle exec kitchen destroy nitrogen
workflows:
  version: 2
  Test:
    jobs:
      - test
